# Generated by Django 4.0.6 on 2022-07-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('coin_symbol', models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Tether', 'Tether'), ('USD Coin', 'USD Coin'), ('BNB', 'BNB'), ('XRP', 'XRP'), ('Binance USD', 'Binance USD'), ('Cardano', 'Cardano'), ('Solana', 'Solana'), ('Dogecoin', 'Dogecoin'), ('Polkadot', 'Polkadot'), ('Shiba Inu', 'Shiba Inu'), ('Polygon', 'Polygon'), ('Avalanche', 'Avalanche'), ('Dai', 'Dai'), ('Lido Staked Ether', 'Lido Staked Ether'), ('TRON', 'TRON'), ('Wrapped Bitcoin', 'Wrapped Bitcoin'), ('LEO Token', 'LEO Token'), ('Litecoin', 'Litecoin'), ('FTX', 'FTX'), ('OKB', 'OKB'), ('Cronos', 'Cronos'), ('Chainlink', 'Chainlink'), ('Uniswap', 'Uniswap'), ('NEAR Protocol', 'NEAR Protocol'), ('Ethereum Classic', 'Ethereum Classic'), ('Cosmos Hub', 'Cosmos Hub'), ('Stellar', 'Stellar'), ('Monero', 'Monero'), ('Algorand', 'Algorand'), ('Bitcoin Cash', 'Bitcoin Cash'), ('Flow', 'Flow'), ('VeChain', 'VeChain'), ('ApeCoin', 'ApeCoin'), ('Theta Fuel', 'Theta Fuel'), ('Chain', 'Chain'), ('Internet Computer', 'Internet Computer'), ('The Sandbox', 'The Sandbox'), ('Decentraland', 'Decentraland'), ('Hedera', 'Hedera'), ('Tezos', 'Tezos'), ('Quant', 'Quant'), ('Filecoin', 'Filecoin'), ('Axie Infinity', 'Axie Infinity'), ('Frax', 'Frax'), ('Elrond', 'Elrond'), ('Aave', 'Aave'), ('Theta Network', 'Theta Network'), ('Helium', 'Helium'), ('TrueUSD', 'TrueUSD'), ('Bitcoin SV', 'Bitcoin SV'), ('EOS', 'EOS'), ('KuCoin', 'KuCoin'), ('cUSDC', 'cUSDC'), ('Huobi BTC', 'Huobi BTC'), ('Maker', 'Maker'), ('BitTorrent', 'BitTorrent'), ('cETH', 'cETH'), ('IOTA', 'IOTA'), ('Fantom', 'Fantom'), ('Lido DAO', 'Lido DAO'), ('The Graph', 'The Graph'), ('THORChain', 'THORChain'), ('Zcash', 'Zcash'), ('Pax Dollar', 'Pax Dollar'), ('eCash', 'eCash'), ('Klaytn', 'Klaytn'), ('Arweave', 'Arweave'), ('Tenset', 'Tenset'), ('Huobi', 'Huobi'), ('Neutrino USD', 'Neutrino USD'), ('Amp', 'Amp'), ('NEO', 'NEO'), ('cDAI', 'cDAI'), ('USDD', 'USDD'), ('Synthetix Network', 'Synthetix Network'), ('Radix', 'Radix'), ('Zilliqa', 'Zilliqa'), ('STEPN', 'STEPN'), ('Basic Attention', 'Basic Attention'), ('DeFiChain', 'DeFiChain'), ('Chiliz', 'Chiliz'), ('Waves', 'Waves'), ('Gate', 'Gate'), ('Stacks', 'Stacks'), ('BitDAO', 'BitDAO'), ('Enjin Coin', 'Enjin Coin'), ('PAX Gold', 'PAX Gold'), ('Loopring', 'Loopring'), ('Kusama', 'Kusama'), ('Dash', 'Dash'), ('ECOMI', 'ECOMI'), ('PancakeSwap', 'PancakeSwap'), ('Convex Finance', 'Convex Finance'), ('Frax Share', 'Frax Share'), ('Curve DAO', 'Curve DAO'), ('NEM', 'NEM'), ('Mina Protocol', 'Mina Protocol'), ('Celo', 'Celo')], default='Bitcoin', max_length=60)),
                ('buy_price', models.IntegerField()),
                ('alert_price', models.IntegerField()),
                ('status', models.CharField(choices=[('C', 'Created'), ('D', 'Deleted'), ('T', 'Triggered')], default='C', max_length=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
