# Generated by Django 4.0.6 on 2022-07-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coinalert_coin_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinalert',
            name='coin_symbol',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Tether', 'Tether'), ('USD Coin', 'USD Coin'), ('BNB', 'BNB'), ('Binance USD', 'Binance USD'), ('XRP', 'XRP'), ('Cardano', 'Cardano'), ('Solana', 'Solana'), ('Dogecoin', 'Dogecoin'), ('Polkadot', 'Polkadot'), ('Polygon', 'Polygon'), ('Shiba Inu', 'Shiba Inu'), ('Dai', 'Dai'), ('Avalanche', 'Avalanche'), ('Lido Staked Ether', 'Lido Staked Ether'), ('TRON', 'TRON'), ('Wrapped Bitcoin', 'Wrapped Bitcoin'), ('LEO Token', 'LEO Token'), ('Litecoin', 'Litecoin'), ('FTX', 'FTX'), ('OKB', 'OKB'), ('Cronos', 'Cronos'), ('Ethereum Classic', 'Ethereum Classic'), ('Chainlink', 'Chainlink'), ('Uniswap', 'Uniswap'), ('NEAR Protocol', 'NEAR Protocol'), ('Cosmos Hub', 'Cosmos Hub'), ('Stellar', 'Stellar'), ('Monero', 'Monero'), ('Algorand', 'Algorand'), ('Bitcoin Cash', 'Bitcoin Cash'), ('Chain', 'Chain'), ('Theta Fuel', 'Theta Fuel'), ('Flow', 'Flow'), ('VeChain', 'VeChain'), ('ApeCoin', 'ApeCoin'), ('The Sandbox', 'The Sandbox'), ('Internet Computer', 'Internet Computer'), ('Decentraland', 'Decentraland'), ('Hedera', 'Hedera'), ('Tezos', 'Tezos'), ('Frax', 'Frax'), ('Quant', 'Quant'), ('Filecoin', 'Filecoin'), ('Axie Infinity', 'Axie Infinity'), ('Aave', 'Aave'), ('Elrond', 'Elrond'), ('TrueUSD', 'TrueUSD'), ('Theta Network', 'Theta Network'), ('Helium', 'Helium'), ('Bitcoin SV', 'Bitcoin SV'), ('EOS', 'EOS'), ('cUSDC', 'cUSDC'), ('KuCoin', 'KuCoin'), ('Huobi BTC', 'Huobi BTC'), ('Pax Dollar', 'Pax Dollar'), ('Maker', 'Maker'), ('THORChain', 'THORChain'), ('BitTorrent', 'BitTorrent'), ('cETH', 'cETH'), ('IOTA', 'IOTA'), ('Fantom', 'Fantom'), ('eCash', 'eCash'), ('Zcash', 'Zcash'), ('The Graph', 'The Graph'), ('Lido DAO', 'Lido DAO'), ('Neutrino USD', 'Neutrino USD'), ('cDAI', 'cDAI'), ('USDD', 'USDD'), ('Huobi', 'Huobi'), ('Klaytn', 'Klaytn'), ('Amp', 'Amp'), ('Arweave', 'Arweave'), ('Tenset', 'Tenset'), ('NEO', 'NEO'), ('Synthetix Network', 'Synthetix Network'), ('Radix', 'Radix'), ('DeFiChain', 'DeFiChain'), ('Gate', 'Gate'), ('Zilliqa', 'Zilliqa'), ('STEPN', 'STEPN'), ('Basic Attention', 'Basic Attention'), ('Chiliz', 'Chiliz'), ('PAX Gold', 'PAX Gold'), ('Stacks', 'Stacks'), ('BitDAO', 'BitDAO'), ('Enjin Coin', 'Enjin Coin'), ('Waves', 'Waves'), ('Kusama', 'Kusama'), ('Loopring', 'Loopring'), ('Dash', 'Dash'), ('ECOMI', 'ECOMI'), ('PancakeSwap', 'PancakeSwap'), ('Curve DAO', 'Curve DAO'), ('Convex Finance', 'Convex Finance'), ('NEM', 'NEM'), ('Frax Share', 'Frax Share'), ('Celo', 'Celo'), ('Mina Protocol', 'Mina Protocol')], default='Bitcoin', max_length=60),
        ),
    ]
